# Generated by Django 2.2.7 on 2021-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('lang', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'Английский'), ('FRA', 'Французский')], default='RUS', max_length=3)),
            ],
        ),
    ]
