# Generated by Django 2.2.7 on 2021-03-12 03:13

from django.db import migrations, models
import django.db.models.deletion
import pushkin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(choices=[('1', 'Проза'), ('2', 'Поэзия')], default='1', max_length=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=pushkin.models.writing_dir_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to='pushkin.Author')),
            ],
        ),
    ]
