# Generated by Django 2.2.7 on 2021-03-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0002_auto_20210312_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='lang',
            field=models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'Английский'), ('FRA', 'Французский')], default='RUS', max_length=3),
        ),
    ]
