# Generated by Django 2.2.7 on 2021-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0003_writing_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writing',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
