# Generated by Django 2.2.7 on 2021-03-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pushkin.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pushkin', '0004_auto_20210314_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writing',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(choices=[('1', 'Проза'), ('2', 'Поэзия')], default='1', max_length=1)),
                ('lang', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'Английский'), ('FRA', 'Французский')], default='RUS', max_length=3)),
                ('file', models.FileField(blank=True, null=True, upload_to=pushkin.models.writing_dir_path)),
                ('active', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='pushkin.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
