# Generated by Django 2.2.7 on 2021-03-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0005_auto_20210315_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='title',
        ),
        migrations.AddField(
            model_name='sample',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='pushkin.Writing'),
        ),
    ]
